#' brms backend plugin
#'
#' This provides an implementation of the brms backend
#' handling the compile/sample split.
#'
#' @return A backend implementation list
#' @export
bg_brms_plugin <- function() {
  list(
    backend_compile = function(params) {
      if (!requireNamespace("brms", quietly = TRUE)) {
        cli::cli_abort("The {.pkg brms} package is required.")
      }

      # brms creates the stan code from the formula.
      # To "compile", we generate the stancode and let brms compile it via empty_data
      # For the MVP mock, we just return the formula structure.
      list(
        compiled = TRUE,
        backend = "brms",
        formula = as.character(params$formula)
      )
    },
    backend_fit = function(compiled_model, data, params) {
      if (!requireNamespace("brms", quietly = TRUE)) {
        cli::cli_abort("The {.pkg brms} package is required.")
      }

      # fit <- brms::brm(compiled_model$formula, data = data, chains = params$chains, ...)
      list(
        fitted = TRUE,
        backend = "brms",
        formula = compiled_model$formula,
        chains = params$chains
      )
    },
    backend_source_hash = function(params) {
      # The source hash for brms is the deterministic stan code generated by the formula and priors
      if (is.null(params$formula)) {
        return("no_formula")
      }

      # In reality: digest::digest(brms::make_stancode(params$formula, ...))
      digest::digest(as.character(params$formula), algo = "sha256")
    },
    backend_runtime_signature = function(params) {
      list(
        fingerprint_fields = list(
          backend = "brms",
          version = if (requireNamespace("brms", quietly = TRUE)) {
            as.character(utils::packageVersion("brms"))
          } else {
            "unknown"
          }
        ),
        compatibility_fields = list(
          os = Sys.info()[["sysname"]]
        )
      )
    }
  )
}
